spring:
  application:
    name: tree-im-robot-service
  datasource:
    url: jdbc:sqlite:/your/path/robot.db:main
    driver-class-name: org.sqlite.JDBC


server:
  port: 8080
  servlet:
    context-path: /im/robot

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true

chat-ai:
  xfxh:
    hostUrl: xxx
    domain: xxx
    temperature: 0.5
    maxTokens: 1024
    maxResponseTime: 30
    QPS: 10
    appId: xxx
    apiKey: xxx
    apiSecret: xxx
  qianfan:
    model: xxx
    temperature: 0.7
    maxTokens: 1024
    maxResponseTime: 30
    accessKey: xxx
    secretKey: xxx


