spring:
  application:
    name: tree-im-robot-service


server:
  port: 8080
  servlet:
    context-path: /im/robot

chat-ai:
  xfxh:
    hostUrl: xxx
    domain: xxx
    temperature: 0.5
    maxTokens: 1024
    maxResponseTime: 30
    QPS: 10
    appId: xxx
    apiKey: xxx
    apiSecret: xxx
  qianfan:
    model: xxx
    temperature: 0.7
    maxTokens: 1024
    maxResponseTime: 30
    accessKey: xxx
    secretKey: xxx


